AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to deploy an EC2 instance, clone a private Git repo, and set up a MAAP app on Docker.

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access.
    Type: String

  InstanceType:
    Description: EC2 instance type.
    Type: String
    Default: t3.medium
    AllowedValues: [t2.micro, t3.medium, t3.large, t3.xlarge]

  AMIId:
    Description: AMI ID for the instance.
    Type: AWS::EC2::Image::Id
    Default: ami-005fc0f236362e99f

  SubnetId:
    Description: Subnet ID to deploy the instance.
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Description: Security Group ID to associate with the instance.
    Type: AWS::EC2::SecurityGroup::Id

  VolumeSize:
    Description: Root volume size in GiB.
    Type: Number
    Default: 100

  TagName:
    Description: Name tag for the EC2 instance.
    Type: String
    Default: MAAP-Fireworks

  IAMInstanceProfile:
    Description: IAM instance profile ARN.
    Type: String

  GitRepoURL:
    Description: HTTP URL for the Git repository.
    Type: String

  MongoDBClusterName:
    Type: String
    Description: The name of the MongoDB Cluster
    Default: "MongoDBCluster-Fireworks"

  MongoDBUserName:
    Type: String
    Description: MongoDB User Name

  MongoDBPassword:
    Type: String
    Description: MongoDB Password

  APIPUBLICKEY:
    Type: String
    Description: MongoDB Atlas API_PUBLIC_KEY

  APIPRIVATEKEY:
    Type: String
    Description: MongoDB Atlas API_PRIVATE_KEY

  GROUPID:
    Type: String
    Description: MongoDB Atlas GROUP_ID

  AWSRegion:
    Description: AWS Region for the EC2 instance.
    Type: String
    Default: us-east-1

  AvailabilityZone:
    Type: String
    Description: EC2 Availability Zone

  FireworksAPIKey:
    Description: Fireworks API Key.
    Type: String

  FireworksModelID:
    Description: Firework model ID of LLM being used.
    Type: String
    Default: accounts/fireworks/models/deepseek-r1

  IMDSv2LaunchTemplateName:
    Description: IMDSv2 Launch Template Name.
    Type: String
    Default: IMDSV2

Resources:
  IMDSv2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Ref IMDSv2LaunchTemplateName
      LaunchTemplateData:
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 2
          HttpTokens: required

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      LaunchTemplate: 
        LaunchTemplateId: !Ref IMDSv2LaunchTemplate
        Version: !GetAtt IMDSv2LaunchTemplate.LatestVersionNumber
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      SubnetId: !Ref SubnetId
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroupIds:
        - !Ref SecurityGroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Ref TagName
        - Key: purpose
          Value: partners
        - Key: owner
          Value: ashwin.gangadhar
        - Key: OwnerContact
          Value: ashwin.gangadhar@mongodb.com
        - Key: expire-on
          Value: 2030-12-31
      IamInstanceProfile: !Ref IAMInstanceProfile


      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail

          LOG_FILE="/home/ubuntu/deployment.log"
          exec > >(tee -a "$LOG_FILE") 2>&1

          echo "Starting instance initialization at $(date)..."

          update_system() {
              echo "Updating system packages..."
              if ! sudo apt update -y; then
                  echo "System update failed. Continuing..."
              fi
          }

          install_packages() {
              echo "Installing required packages..."
              if ! sudo apt install -y python3 python3-pip git docker.io docker-compose ksh python3-venv; then
                  echo "Package installation failed. Continuing..."
              fi
          }

          configure_docker() {
              echo "Configuring Docker..."
              if ! sudo usermod -aG docker ubuntu; then
                  echo "Failed to add user to Docker group. Continuing..."
              fi
          }

          clone_repository() {
              echo "Cloning Git repository..."
              if ! sudo -u ubuntu git clone "${GitRepoURL}" /home/ubuntu/MAAP-Files; then
                  { echo "Git clone failed.  Exiting."; exit 1; }
              fi
              cd /home/ubuntu/MAAP-Files || { echo "MAAP-Files directory not found. Exiting."; exit 1; }
          }

          setup_main_env_file() {
              echo "Setting up environment variables..."
              HOST_ADD=`curl -s ifconfig.me`
              cat <<EOF > /home/ubuntu/MAAP-Files/.env
          AWS_REGION=${AWSRegion}
          API_PUBLIC_KEY=${APIPUBLICKEY}
          API_PRIVATE_KEY=${APIPRIVATEKEY}
          GROUP_ID=${GROUPID}
          FIREWORKS_API_KEY=${FireworksAPIKey}
          FIREWORKS_MODEL_ID=${FireworksModelID}         
          NEXT_PUBLIC_API_URL=http://$HOST_ADD:5001
          EOF
          chown ubuntu:ubuntu "/home/ubuntu/MAAP-Files/.env" || echo "Failed to change ownership of .env file."
          chmod 755 "/home/ubuntu/MAAP-Files/.env" || echo "Failed to set executable permission for .env file."

          }

          deploy_mongodb() {
              echo "Deploying MongoDB cluster..."
              chmod +x mongodb_cluster_manager.ksh || echo "Failed to set executable permission for mongodb_cluster_manager.ksh."
              if ! ./mongodb_cluster_manager.ksh deploy "${MongoDBClusterName}" "${MongoDBUserName}" "${MongoDBPassword}"; then
                  { echo  "MongoDB cluster deployment failed. Exiting."; exit 1; }
              fi
          }

          pull_docker_images() {
              echo "Pulling Docker images..."
              docker-compose -f docker-compose-ecr.yaml pull || { echo "Docker Compose pull failed. Exiting."; exit 1; }
          }

          deploy_services() {
              echo "Building and Starting Docker services..."

              docker-compose build

              if ! docker-compose up -d; then
                  { echo "Docker Compose failed to start services. Exiting."; exit 1; }
              fi

          }

          main() {
              update_system
              install_packages
              configure_docker
              clone_repository
              setup_main_env_file
              deploy_mongodb
              deploy_services
              echo "Instance initialization completed at $(date)."
          }

          main

Outputs:
  InstanceId:
    Description: Instance ID of the deployed EC2 instance.
    Value: !Ref EC2Instance

  PublicDNS:
    Description: Public DNS of the deployed EC2 instance.
    Value: !GetAtt EC2Instance.PublicDnsName

  EC2PublicIP:
    Description: Public IPv4 address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
